version: '3'

networks:
  apache_net:
    ipam:
      config:
        - subnet: 10.9.0.0/24
services:
  apache:
    image: vovolinux/apache2-php5.6
    container_name: apache2-php5.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    networks:
      apache_net:
        ipv4_address: 10.9.0.2

  postgres:
    container_name: ${POSTGRES_DB}
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/${POSTGRES_DB}:/var/lib/postgresql/data/pgdata
    networks:
      apache_net:
        ipv4_address: 10.9.0.3
  