version: '3'

networks:
  apache_net:
    ipam:
      config:
        - subnet: 10.9.0.0/24
services:
  apache:
    image: vovolinux/apache2-php5.6:1.0
    container_name: apache2-php5.6
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./apache2/conf/apache2.conf:/etc/apache2/apache2.conf
      - ./apache2/sites-available:/etc/apache2/sites-available
    networks:
      apache_net:
        ipv4_address: 10.9.0.2
