version: '3'

services:
  postgres-alpine:
    container_name: postgres-alpine
    image: vovolinux/postgres-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data/pgdata"
      
# On my machine, it works!
# (Vovolinux)
