version: '3'

services:
  test-database-dev:
    container_name: postgres13
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres/pgdata:/var/lib/postgresql/data/pgdata"
